[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "mobile/dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[dev]
  framework = "#static"
  port = 9000
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
